DROP TABLE IF EXISTS audit_log; DROP TABLE IF EXISTS archives; DROP TABLE IF EXISTS webhook_deliveries; DROP TABLE IF EXISTS webhooks; DROP TABLE IF EXISTS monitoring_events; DROP TABLE IF EXISTS monitoring_enrollments; DROP TABLE IF EXISTS alert_acknowledgements; DROP TABLE IF EXISTS alerts; DROP TABLE IF EXISTS schedule_runs; DROP TABLE IF EXISTS schedules; DROP TABLE IF EXISTS rule_runs; DROP TABLE IF EXISTS rule_actions; DROP TABLE IF EXISTS rule_conditions; DROP TABLE IF EXISTS rules; DROP TABLE IF EXISTS scene_actions; DROP TABLE IF EXISTS scenes; DROP TABLE IF EXISTS device_commands; DROP TABLE IF EXISTS telemetry; DROP TABLE IF EXISTS device_tokens; DROP TABLE IF EXISTS devices; DROP TABLE IF EXISTS memberships; DROP TABLE IF EXISTS homes; DROP TABLE IF EXISTS users;
CREATE TABLE users(id INTEGER PRIMARY KEY,email TEXT UNIQUE,password TEXT,name TEXT,role TEXT,active INTEGER DEFAULT 1);
CREATE TABLE homes(id INTEGER PRIMARY KEY,name TEXT,timezone TEXT,address_label TEXT,owner_user_id INTEGER,created_at TEXT);
CREATE TABLE memberships(id INTEGER PRIMARY KEY,home_id INTEGER,user_id INTEGER,home_role TEXT,status TEXT,created_at TEXT,UNIQUE(home_id,user_id));
CREATE TABLE devices(id INTEGER PRIMARY KEY,home_id INTEGER,name TEXT,device_type TEXT,capabilities TEXT,status TEXT,last_seen_at TEXT,firmware TEXT,external_id TEXT UNIQUE);
CREATE TABLE device_tokens(id INTEGER PRIMARY KEY,device_id INTEGER,token TEXT UNIQUE,created_at TEXT,revoked_at TEXT);
CREATE TABLE telemetry(id INTEGER PRIMARY KEY,device_id INTEGER,source_event_id TEXT,metric TEXT,value REAL,text_value TEXT,reported_at TEXT,received_at TEXT,UNIQUE(device_id,source_event_id));
CREATE TABLE device_commands(id INTEGER PRIMARY KEY,device_id INTEGER,actor_user_id INTEGER,command TEXT,payload TEXT,status TEXT,created_at TEXT,completed_at TEXT);
CREATE TABLE scenes(id INTEGER PRIMARY KEY,home_id INTEGER,name TEXT,active INTEGER DEFAULT 1,created_by INTEGER,created_at TEXT);
CREATE TABLE scene_actions(id INTEGER PRIMARY KEY,scene_id INTEGER,device_id INTEGER,command TEXT,payload TEXT,sequence_no INTEGER);
CREATE TABLE rules(id INTEGER PRIMARY KEY,home_id INTEGER,name TEXT,enabled INTEGER DEFAULT 1,trigger_device_id INTEGER,trigger_metric TEXT,trigger_operator TEXT,trigger_value TEXT,priority INTEGER,cooldown_sec INTEGER,last_run_at TEXT,created_by INTEGER);
CREATE TABLE rule_conditions(id INTEGER PRIMARY KEY,rule_id INTEGER,device_id INTEGER,metric TEXT,operator TEXT,comparison_value TEXT);
CREATE TABLE rule_actions(id INTEGER PRIMARY KEY,rule_id INTEGER,device_id INTEGER,command TEXT,payload TEXT,sequence_no INTEGER);
CREATE TABLE rule_runs(id INTEGER PRIMARY KEY,rule_id INTEGER,trigger_event_id TEXT,status TEXT,details TEXT,started_at TEXT,completed_at TEXT);
CREATE TABLE schedules(id INTEGER PRIMARY KEY,home_id INTEGER,name TEXT,timezone TEXT,cron_hour INTEGER,cron_minute INTEGER,weekday_mask TEXT,scene_id INTEGER,rule_id INTEGER,enabled INTEGER DEFAULT 1,last_run_date TEXT);
CREATE TABLE schedule_runs(id INTEGER PRIMARY KEY,schedule_id INTEGER,scheduled_for TEXT,status TEXT,details TEXT,created_at TEXT);
CREATE TABLE alerts(id INTEGER PRIMARY KEY,home_id INTEGER,device_id INTEGER,kind TEXT,severity TEXT,message TEXT,status TEXT,dedup_key TEXT,created_at TEXT,resolved_at TEXT);
CREATE TABLE alert_acknowledgements(id INTEGER PRIMARY KEY,alert_id INTEGER,user_id INTEGER,note TEXT,created_at TEXT);
CREATE TABLE monitoring_enrollments(id INTEGER PRIMARY KEY,home_id INTEGER,status TEXT,contact_name TEXT,contact_phone TEXT,created_at TEXT);
CREATE TABLE monitoring_events(id INTEGER PRIMARY KEY,enrollment_id INTEGER,alert_id INTEGER,event_type TEXT,status TEXT,details TEXT,created_at TEXT);
CREATE TABLE webhooks(id INTEGER PRIMARY KEY,home_id INTEGER,name TEXT,target_url TEXT,secret TEXT,event_types TEXT,active INTEGER DEFAULT 1);
CREATE TABLE webhook_deliveries(id INTEGER PRIMARY KEY,webhook_id INTEGER,event_id TEXT,payload TEXT,status TEXT,attempt INTEGER,response_code INTEGER,created_at TEXT,next_retry_at TEXT);
CREATE TABLE archives(id INTEGER PRIMARY KEY,home_id INTEGER,kind TEXT,record_count INTEGER,path TEXT,created_at TEXT);
CREATE TABLE audit_log(id INTEGER PRIMARY KEY,actor_user_id INTEGER,action TEXT,object_type TEXT,object_id TEXT,details TEXT,created_at TEXT);
CREATE INDEX idx_telemetry_device_time ON telemetry(device_id,reported_at); CREATE INDEX idx_alerts_home_status ON alerts(home_id,status);
